name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: prepare
      run: sudo apt-get update -y && sudo apt-get install -y libcriterion-dev 
    - name: run test
      run: make test
